# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Opm < Formula
  desc "OpenCode profile manager — switch configs like docker context"
  homepage "https://github.com/tbcrawford/opm"
  version "1.0.0"
  license "MIT"

  on_macos do
    url "https://github.com/tbcrawford/opm/releases/download/v1.0.0/opm_1.0.0_darwin_all.tar.gz"
    sha256 "50134a0193f94ac7ec2589225f1407aeee4573dd306ce4f2168aa9e6bd405af1"

    define_method(:install) do
      bin.install "opm"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tbcrawford/opm/releases/download/v1.0.0/opm_1.0.0_linux_amd64.tar.gz"
      sha256 "3d9fef50434dea43d1a77efbe120c7f23a30961ee1f7d5d101c2ae624257a143"
      define_method(:install) do
        bin.install "opm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tbcrawford/opm/releases/download/v1.0.0/opm_1.0.0_linux_arm64.tar.gz"
      sha256 "902556b7f3276b88ec47f3610bf06b56cd865dced89f19e672520798b834465e"
      define_method(:install) do
        bin.install "opm"
      end
    end
  end

  test do
    system "#{bin}/opm", "--version"
  end
end
