# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Opm < Formula
  desc "OpenCode profile manager — switch configs like docker context"
  homepage "https://github.com/tbcrawford/opm"
  version "1.2.0"
  license "MIT"

  on_macos do
    url "https://github.com/tbcrawford/opm/releases/download/v1.2.0/opm_1.2.0_darwin_all.tar.gz"
    sha256 "bde4e39039d6af32fdf502eec9a862240cb35c94497e27636649990820b1003d"

    define_method(:install) do
      bin.install "opm"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tbcrawford/opm/releases/download/v1.2.0/opm_1.2.0_linux_amd64.tar.gz"
      sha256 "deda4b2bc25901596a5616186499a9436174274c2d7404fbc71a4752096ed41b"
      define_method(:install) do
        bin.install "opm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tbcrawford/opm/releases/download/v1.2.0/opm_1.2.0_linux_arm64.tar.gz"
      sha256 "4723a7385d9288219550e60392f911abd4cd5a5c2941404a21d060eb4ecd4fd0"
      define_method(:install) do
        bin.install "opm"
      end
    end
  end

  test do
    system "#{bin}/opm", "--version"
  end
end
