# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Opm < Formula
  desc "OpenCode profile manager — switch configs like docker context"
  homepage "https://github.com/tbcrawford/opm"
  version "0.1.0"
  license "MIT"

  on_macos do
    url "https://github.com/tbcrawford/opm/releases/download/v0.1.0/opm_0.1.0_darwin_all.tar.gz"
    sha256 "51ff8bfc5314577b555e4a08a9c49c84f26cc8d129b9dd8e8b9f85783685e4c5"

    define_method(:install) do
      bin.install "opm"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tbcrawford/opm/releases/download/v0.1.0/opm_0.1.0_linux_amd64.tar.gz"
      sha256 "fac46f2b7c81ebed18f07eac02af2a6e5123f24ae4421f23b18d62f653bcecaf"
      define_method(:install) do
        bin.install "opm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tbcrawford/opm/releases/download/v0.1.0/opm_0.1.0_linux_arm64.tar.gz"
      sha256 "0928633dc81ffa11acdabc0acb51e7efea8dfdf7bd7cfc8d1ed6f5023964b744"
      define_method(:install) do
        bin.install "opm"
      end
    end
  end

  test do
    system "#{bin}/opm", "--version"
  end
end
